name: farmacia_monitor
description: Monitor de temperatura para farmacias
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # MQTT
  mqtt_client: ^10.2.1

  # Gráficos
  fl_chart: ^0.68.0

  # Notificaciones locales
  flutter_local_notifications: ^17.2.2

  # Background service — versión estable para Android 12


  # Almacenamiento local
  shared_preferences: ^2.2.3

  # Formato de fechas
  intl: ^0.19.0

  # Íconos
  cupertino_icons: ^1.0.6
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
